Add project content features
BenMKT/Hello-Microverse pull request #1
Opened 2023-05-30 22:00 UTC by BenMKT

The following were added to my project:

-     HTML & CSS linters.
-     A descriptive README file.
-     index.html & styles.css files with relevant code context.
-     Added `test.md` file to `.gitignore` file and also node_modules.

2023-05-30 22:40 UTC, Efiamotu-1 requested changes
Hi @BenMKT , 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 22:40 UTC, Efiamotu-1 commented on README.md
- your project's readme is curently missing a couple of important sections kindly read the description below on the best way to create your professional readme :+1: 
- * [ ]  For the project requirements, kindly ensure that your README file is descriptive and professional. And the required template to be used here is the **[Microverse README template](https://github.com/microverseinc/readme-template)**, so ensure that:
* All main headers from the [README template](https://github.com/microverseinc/readme-template) are present in a your repo.
* The only optional section is `FAQ`
* you delete the `live demo` section if the you decide not to deploy the application.
* Make sure the you have added the section `Future Features`, including 1-3 potential features to be added.
* you remove the section `description`, i.e.` "> Describe the tech stack and include only the relevant sections that apply to your project."` should be removed and filled in with their custom content.
* you remove template logo. Optionally, the you can replace it with your own logo you they have one.
* No broken link or image
- for further assistance see this [students repo for his descriptive readme](https://github.com/Mike111222/Hello-Microverse-Project/blob/main/README.md)

2023-05-31 00:21 UTC, jmonto55 requested changes
# STATUS: REQUIRED CHANGES 🟡

Hi @BenMKT 👋🏽, 

Great work on making the changes requested by a previous reviewer 👌
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![AlmostThereGIF](https://user-images.githubusercontent.com/116701485/232347631-60851d91-4b6b-4c48-aa78-13e4bc4dc267.gif)



 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 00:21 UTC, jmonto55 commented on README.md
> +  <br/>
- [ ] Great work implementing your professional README file 💯. However, please kindly ensure to remove the Microverse logo from here🤓.

2023-05-31 03:54 UTC, abdallahmalima approved these changes
Hi @BenMKT , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter Errors✔
- Descriptive PR title and description✔
-  GitHub flow✔
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 13:39 UTC, merged